name: authnull
description: Authnull Flutter implements, use a single login method for all service you loved.
version: 1.4.0
homepage: https://authnull.com

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  brontosaurus_flutter: ^1.2.1
  device_info: ^0.4.1+4
  firebase_auth: ^0.15.4
  http: ^0.12.0+4
  google_sign_in: ^4.1.1
  shared_preferences: ^0.5.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.authnull.authnull
        pluginClass: AuthnullPlugin
      ios:
        pluginClass: AuthnullPlugin
      linux:
        pluginClass: AuthnullPlugin
      macos:
        pluginClass: AuthnullPlugin
      windows:
        pluginClass: AuthnullPlugin
