name: authnull
description: A new flutter plugin project.
version: 1.1.2
homepage: https://authnull.com

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  brontosaurus_flutter: ^1.0.0
  device_info: ^0.4.1+4
  firebase_auth: ^0.15.4
  http: ^0.12.0+4
  google_sign_in: ^4.1.1
  shared_preferences: ^0.5.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.authnull.authnull
    pluginClass: AuthnullPlugin
